import { Component, OnInit, Input } from '@angular/core';
@Component({
  selector: 'app-heroes',
  templateUrl: './heroes.component.html',
  styleUrls: ['./heroes.component.scss']
})
export class HeroesComponent implements OnInit {
showClientes(){
  this.showingClientes = true
  this.showingProdutos = false
  this.showingQuants = false
}
showProdutos(){
  this.showingClientes = false
  this.showingProdutos = true
  this.showingQuants = false
}
showQuants(){
  this.showingClientes = false
  this.showingProdutos = false
  this.showingQuants = true
}
showingClientes = true;
showingProdutos = false;
showingQuants = false;

clientes=[
  'Blade',
'Capitão América',
'Doutor Estranho ',
'Feiticeira Escarlate',
'Guardiões da Galáxia',
'Homem de Ferro',
'Homem-Aranha',
'Hulk',
'Os Vingadores',
'Quarteto Fantástico',
'Thor',
'Wolverine',
'Adam Warlock',
'Agente Americano',
'Agente X',
'Al MacKenzie',
'Alaris',
'Alfazema',
'Alias',
'Amadeus Cho',
'Amazing-Man',
'Angela',
'Apache Kid',
'Gertrude Yorkes',
'Asa de Fogo ',
'Banshee',
'Batal ',
'Ben Reilly',
'Bereet',
'Bill Raio Beta',
'Bishop ',
'Black Rider ',
'Blade  ',
'Bling! ',
'Box  ',
'Bucky ',
'Camaleão ',
'Capitão América ',
'Capitão Britânia ',
'Captain Marvel ',
'Capitão Universo ',
'Carmilla Black ',
'Cavaleiro Fantasma ',
'Cavaleiro Negro ',
'Chama Solar ',
'Charlie-27 ',
'Chase Stein ',
'Ciclope ',
'Coisa ',
'Colleen Wing ',
'Colossus ',
'Comando Selvagem ',
'Conan ',
'Crescente ',
'Cristal ',
'Cristalys ',
'Defensores ',
'Demolição ',
'Demolidor ',
'Doutor Estranho ',
'Doutor Spectrum ',
'Doutor Druida ',
'Elektra Natchios ',
'Excelsior ',
'Faísca ',
'Falcão de Aço ',
'Fandral ',
'Fantomex ',
'Fera ',
'Firestar ',
'Fóton ',
'Frankenstein ',
'Franklin Richards ',
'Fugitivos ',
'Gambit ',
'Gamora ',
'Garota Esquilo ',
'Gaviã Arqueira ',
'Gorgon ',
'Groot ',
'Guardião Vermelho ',
'Harpia ',
'Heróis de Aluguel ',
'Homem 3-D ',
'Homem-Areia ',
'Homem de Gelo ',
'Homem-Máquina ',
'Homem-Coisa ',
'Homem-Formiga ',
'Hope Pym ',
'Howard, o Pato ',
'Inumanos ',
'Jane Foster ',
'Jarella ',
'Jean Grey ',
'Jeffrey Mace ',
'Jessica Jones ',
'Daisy Johnson ',
'Jovens Vingadores ',
'Jubileu ',
'Julie Power ',
'Justice ',
'Ka-Zar ',
'Kamala Khan ',
'Karolina Dean ',
'Kid Cassidy & Reno Jone ',
'Kid Colt ',
'Killraven ',
'Kitty Pryde ',
'Klara Prast ',
'Kraven ',
'Lagarto ',
'Lei Kung ',
'Lei Ling ',
'Leiko Wu ',
'Lin Lie ',
'Lockheed ',
'Luke Cage ',
'Luna Snow ',
'Lyja ',
'Magnum ',
'Manikin ',
'Manto e Adaga ',
'Máquina de Combate ',
'Mar-Vell ',
'Maria Hill ',
'Maria Stark ',
'Martinex ',
'Marvel Boy ',
'Mattie Franklin ',
'Shang-Chi ',
'Micromax ',
'Miles Morales ',
'Miragem ',
'Míssil ',
'Molly Hayes ',
'Monica Rambeau ',
'Mulher-Aranha ',
'Mulher-Hulk ',
'Mulher Invisível ',
'Nick Fury ',
'Nico Minoru ',
'Noh-Varr ',
'Noturno ',
'Nova ',
'Nova ',
'Okoye ',
'Outlaw Kid ',
'Pantera Negra ',
'Pássaro da Neve ',
'Peggy Carter ',
'Polaris ',
'Primaz ',
'Professor Charles Xavier ',
'Psylocke ',
'Punho de Ferro ',
'Quarteto Futuro ',
'Radical ',
'Radius ',
'Raio Negro ',
'Raposa Branca ',
'Raposa Prateada ',
'Rawhide Kid ',
'Riri Williams ',
'Rocket Raccoon ',
'Rom, o Cavaleiro do Espaço ',
'Sabre de Prata ',
'Senhor Fantástico ',
'Sentinela ',
'Sersi ',
'Sharon Carter ',
'Sharon Rogers  ',
'Sharon Ventura ',
'Shuri ',
'Sif ',
'Silk ',
'Siryn ',
'Mancha Solar (personagem) ',
'Solaris ',
'Soprano ',
'Spider-Girl ',
'Spider-Ham ',
'Spider-Woman ',
'Spyke ',
'Senhor das Estrelas ',
'Starfox ',
'Starhawk ',
'Surfista Prateado ',
'Tempestade ',
'Thena ',
'Thor ',
'Tocha Humana ',
'Tocha Humana (original) ',
'Tropa Alfa ',
'Tropa Beta ',
'Tropa Gama ',
'Two-Gun Kid ',
'Uatu, o Vigia ',
'Union Jack  ',
'Valéria Richards ',
'Vespa ',
'Victor Mancha ',
'Visão ',
'Warren Worthington III ',
'Wave ',
'Wolverine ',
'Jimmy Woo ',
'X-Factor ',
'X-Statix ',
'Xavin ',
'Yo-Yo Rodriguez ',
'Yondu '
]

  constructor() { }
  ngOnInit(): void {
  }
}
